apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app-name: webapp
    version: "5"

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

